### ISSUE TITLE
shortcut not working?

### ISSUE THREAD

**Issue by bluenote10** [vnphanquang/svelte-put#125]
I tried to make use of `shortcut` but it simply doesn't seem to do nothing. I'm simply trying (with appropriate imports and `handleK` definition):

```ts
<div
  use:shortcut={{
    trigger: {
      key: "k",
      callback: handleK,
    },
  }}
/>
```

but the callback simply never gets called. I tried other keys as well without luck. No errors are visible from the console.

Any ideas what could be wrong or how to debug why it isn't working?

**Comment by vnphanquang** [comment]
@bluenote10 try `<svelte:window>` instead of `div`:

```html
<svelte:window
  use:shortcut={{
    trigger: {
      key: "k",
      callback: handleK,
    },
  }}
/>
```

By default div doesn't accept focus, so if your div doesn't have any focusable content, it won't receive any keyboard event. I should have clarify / use `svelte:window` in the docs, sorry about that.

FWIW, to verify this, you can add an input to your div, focus on that input, then hit `k`, which should trigger your callback

```html
<div
  use:shortcut={{
    trigger: {
      key: "k",
      callback: handleK,
    },
  }}
/>
```

Hope that helps. Let me know

**Comment by bluenote10** [comment]
Thanks for the clarification, attaching it to `svelte:window` indeed works fine -- I was just thinking it doesn't matter where to attach it to, because the docs use it on regular divs.

**Comment by vnphanquang** [comment]
@bluenote10 yeah, key listener will be attached to the element on which the action is used. I've modified the docs to use `svelte:window`.
